# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "ehci_pci" "usbhid" "sd_mod" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/ecd43d8d-4456-448d-9e4f-8dbc21c7717a";
      fsType = "ext4";
    };

  fileSystems."/hugetlbfs" =
    { device = "hugetlbfs";
      fsType = "hugetlbfs";
    };

  fileSystems."/var/lib/docker/devicemapper" =
    { device = "/var/lib/docker/devicemapper";
      fsType = "none";
      options = [ "bind" ];
    };

  swapDevices = [ ];

  nix.maxJobs = lib.mkDefault 6;
}
